# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/focal64"
  config.vm.define "bigiamongodb"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "bigiamongodb"
  end
  #Puerto por defecto
  #config.vm.network "private_network", ip: "192.168.33.103"
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  #Carpeta por defecto
  #config.vm.synced_folder "data", "/data/db"

  #Provision (comentadas líneas para xenial64)
  config.vm.provision "shell", inline: <<-SHELL
    #sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    #sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv D68FA50FEA312927
    #echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    # Otro manual de instalación: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
    # Instrucciones para repo directo de MongoDB (no repo por defecto de la distro)
    cd /home/vagrant
    wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    sudo sed -i "s/bindIp: 127.0.0.1/bindIp: ::,0.0.0.0/" /etc/mongod.conf
    # Solo si se monta interfaz de red interna
    #sed -i "s/bindIp: 127.0.0.1/bindIp: 127.0.0.1,192.168.33.103/" /etc/mongod.conf
    #Para versión anterior de mongo
    #sudo locale-gen
    #sudo locale-gen en_US.UTF-8
    #sudo locale-gen es_ES.UTF-8
    #sudo localedef -i es_ES -f UTF-8 es_ES.UTF-8
    sudo service mongod start
    sudo systemctl enable mongod.service
    gunzip /vagrant/dpc-covid19-ita-province.json.gz
    mongoimport --db covid --collection coviditalia --file /vagrant/dpc-covid19-ita-province.json --jsonArray
  SHELL

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

end
