# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 6379, host: 6379
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
    apt-get update
    apt-get install -y lsb-release
    apt-get install -y redis
#    sudo sed -i "s/protected mode yes/protected mode no/" /etc/redis/redis.conf
    sed -i "s/# requirepass foobared/requirepass 123quetal123/" /etc/redis/redis.conf
    sed -i "s/protected-mode yes/protected-mode no/" /etc/redis/redis.conf
    sed -i "s/bind 127.0.0.1 -::1/bind * -::*/" /etc/redis/redis.conf
    systemctl enable redis-server.service
    service redis-server restart
    echo -e "config set requirepass 123quetal123\nAUTH 123quetal123\nPING" | redis-cli
  SHELL
end
